image bg_entrada = Transform("images/entrada.jpg", xysize=(1920, 1080))
image bg_escaleras = Transform("images/escaleras.jpg", xysize=(1920, 1080))
image bg_patio = Transform("images/patio.jpg", xysize=(1920, 1080))
image bg_fachadita = Transform("images/fachadita.jpg", xysize=(1920, 1080))
image bg_pasadiso = Transform("images/pasadiso.jpg", xysize=(1920, 1080))

image unknown alberto = Transform("images/unknown_alberto.png", zoom=2.5)

image dorian happy = Transform("images/dorian_happy.png", zoom=0.3)
image dorian question = Transform("images/dorian_question.png", zoom=2)
image dorian pro = Transform("images/dorian_pro.png", zoom=2.2)
image dorian direccion = Transform("images/dorian_direccion.png", zoom=2)
image dorian pensando = Transform("images/dorian_duda.png", zoom=0.4)
image dorian duda = Transform("images/dorian_duda.png", zoom=0.4)
image dorian emocionado = Transform("images/dorian_emocionado.png", zoom=0.4)
image dorian feliz = Transform("images/dorian_feliz.png", zoom=0.4)
image dorian poker = Transform("images/dorian_poker.png", zoom=0.4)
image dorian saludo = Transform("images/dorian_saludo.png", zoom=0.4)
image dorian triste = Transform("images/dorian_triste.png", zoom=0.4)
image dorian convencido = Transform("images/dorian_convencido.png", zoom=0.4)


# image alberto normal = "images/alberto_normal.png"
image alberto enojado = Transform("images/alberto_enojado.png", zoom=2)
image alberto feliz = Transform("images/alberto_feliz.png", zoom=2)
image alberto riendo = Transform("images/alberto_alegre.png", zoom=0.4)
image alberto alegre = Transform("images/alberto_alegre.png", zoom=0.4)
image alberto duda = Transform("images/alberto_duda.png", zoom=0.4)
image alberto emocionado_ultra = Transform("images/alberto_emocionado_ultra.png", zoom=0.4)
image alberto emocionado = Transform("images/alberto_emocionado.png", zoom=0.4)
image alberto miedo = Transform("images/alberto_miedo.png", zoom=0.4)
image alberto pensando = Transform("images/alberto_pensando.png", zoom=0.4)
image alberto sonroja = Transform("images/alberto_sonrojado.png", zoom=0.4)
image alberto dolor = Transform("images/alberto_sufriendo.png", zoom=0.4)
image alberto sufriendo = Transform("images/alberto_sufriendo.png", zoom=0.4)
image alberto triste = Transform("images/alberto_triste.png", zoom=0.4)
image alberto uwu = Transform("images/alberto_uwu.png", zoom=0.4)

image alberto caida1 = Transform("images/caida_1.png", zoom=0.5)
image alberto caida2 = Transform("images/caida_2.png", zoom=0.5)
image alberto caida3 = Transform("images/caida_3.png", zoom=0.5)
image alberto caida4 = Transform("images/caida_4.png", zoom=0.5)
image alberto caida5 = Transform("images/caida_5.png", zoom=0.5)


image clari poker = Transform("images/clari_normal.png", zoom=2.2)
image clari normal = Transform("images/clari_normal.png", zoom=0.5)
image clari feliz = Transform("images/clari_feliz.png", zoom=0.4)
image clari enojada = Transform("images/clari_gritar.png", zoom=0.4)
image clari gritar = Transform("images/clari_gritar.png", zoom=0.4)
image clari duda = Transform("images/clari_pensando.png", zoom=0.4)
image clari pensando = Transform("images/clari_pensando.png", zoom=0.4)
image clari preocupada = Transform("images/clari_preocupada.png", zoom=0.4)
image clari triste = Transform("images/clari_triste.png", zoom=0.4)
image clari emocionado = Transform("images/clari_emocionado.png", zoom=0.4)


image maycol normal = Transform("images/maycol_normal.png", zoom=2)

image jose normal = Transform("images/jose_normal.png", zoom=2)